### ISSUE TITLE
Application doesn't handle non-ASCII characters

### ISSUE THREAD

**Issue by james2432** [CUTR-at-USF/gtfs-osm-sync#25]
Characters like èÈéÉ etc are not currently handled when downloading from OSM
Will create pull request

**Comment by barbeau** [comment]
@james2432 Thanks for filing this bug!  Do you have a stack trace or any other information about what currently happens when it doesn't handle non-ASCII characters correctly?

It would be good to document this if possible.

**Comment by james2432** [comment]
It makes the characters render incorrectly. Like in the image below, "DE LA CITÉ & DE LA GAPPE" appears as "DE LA CITÃ%...." and from osm it says "De la CitÃ©". This is due to invalid decoding as the old method was using default charsets defined by the operating system and may not be UTF8 (highly likely on windows machines)
![go-sync](https://cloud.githubusercontent.com/assets/498547/15252942/13749cb4-18fe-11e6-8d35-847f5a405f22.PNG)

**Comment by barbeau** [comment]
Perfect!
